"""update_lesson_model

Revision ID: 0019e990a193
Revises: 2348e1f8723d
Create Date: 2024-11-23 16:53:11.459006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0019e990a193'
down_revision: Union[str, None] = '2348e1f8723d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lessons_course_id_fkey', 'lessons', type_='foreignkey')
    op.create_foreign_key(None, 'lessons', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.create_foreign_key('lessons_course_id_fkey', 'lessons', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###
