"""course_image

Revision ID: 03ec7c17e380
Revises: 5a72cb7a0b0d
Create Date: 2024-12-16 20:24:56.006777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ec7c17e380'
down_revision: Union[str, None] = '5a72cb7a0b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('image_path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'image_path')
    # ### end Alembic commands ###
