"""status_course_enable

Revision ID: 3c2b791eb50f
Revises: c64993f5a436
Create Date: 2024-12-10 11:43:50.397074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2b791eb50f'
down_revision: Union[str, None] = 'c64993f5a436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('staus', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', 'IN_REVIEW', name='coursestatusenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'staus')
    # ### end Alembic commands ###
