"""lesson_model_update

Revision ID: 56df32632428
Revises: 0019e990a193
Create Date: 2024-11-23 19:46:41.814072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56df32632428'
down_revision: Union[str, None] = '0019e990a193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('slug', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'lessons', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='unique')
    op.drop_column('lessons', 'slug')
    # ### end Alembic commands ###
