"""status_typo

Revision ID: 5a72cb7a0b0d
Revises: bd4df98f0b9b
Create Date: 2024-12-10 12:12:16.069313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a72cb7a0b0d'
down_revision: Union[str, None] = 'bd4df98f0b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', 'IN_REVIEW', 'READY', name='coursestatusenum'), nullable=True))
    op.drop_column('courses', 'staus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('staus', postgresql.ENUM('draft', 'published', 'archived', 'in_review', name='coursestatusenum'), autoincrement=False, nullable=True))
    op.drop_column('courses', 'status')
    # ### end Alembic commands ###
