"""account_disabled_add

Revision ID: 60c4e38d8409
Revises: 1986fbe9ac88
Create Date: 2024-11-22 16:38:37.748409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c4e38d8409'
down_revision: Union[str, None] = '1986fbe9ac88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'disabled')
    # ### end Alembic commands ###
