"""status_course

Revision ID: 7f6318c6b5d6
Revises: c9be08165f27
Create Date: 2024-12-10 11:05:45.876026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f6318c6b5d6'
down_revision: Union[str, None] = 'c9be08165f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('staus', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', 'IN_REVIEW', name='coursestatusenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'staus')
    # ### end Alembic commands ###
