"""meta_course

Revision ID: ae8ca807bc0a
Revises: 508c22d1dd29
Create Date: 2024-12-16 21:49:22.511783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae8ca807bc0a'
down_revision: Union[str, None] = '508c22d1dd29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meta', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meta', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meta', type_='foreignkey')
    op.drop_column('meta', 'course_id')
    # ### end Alembic commands ###
