"""status_course

Revision ID: c64993f5a436
Revises: 7f6318c6b5d6
Create Date: 2024-12-10 11:43:16.808729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c64993f5a436'
down_revision: Union[str, None] = '7f6318c6b5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'staus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('staus', postgresql.ENUM('draft', 'published', 'archived', 'in_review', name='coursestatusenum'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
