"""add_account_in_course

Revision ID: c9be08165f27
Revises: f3ecb4785823
Create Date: 2024-12-08 16:46:10.533048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9be08165f27'
down_revision: Union[str, None] = 'f3ecb4785823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'accounts', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'created_by')
    # ### end Alembic commands ###
