"""lesson_video_url

Revision ID: eba7f3a5c14d
Revises: 926bb091bf77
Create Date: 2024-12-05 13:35:23.429395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba7f3a5c14d'
down_revision: Union[str, None] = '926bb091bf77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('video_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'video_url')
    # ### end Alembic commands ###
